### ISSUE TITLE
Track (flac) don't start playing after automatic track conversion

### ISSUE THREAD

**Issue by lowlow---** [Sonerezh/sonerezh#138]
Hi, 
When I click the "play button" of an album or a track that need conversion, the track is effectively converted (by ffmpeg in my case, I see a CPU usage bump and a mp3 is created in app/tmp) but the track isn't played.

By the way, it would be nice to convert in advance all the track of the current queue ...

**Comment by ltGuillaume** [comment]
Same here. I get the following entries in error.log:

> 2016-06-08 09:35:57 Error: [NotFoundException] The requested file was not found
Request URL: /songs/download/18943
Stack Trace:
#0 /srv/http/sonerezh/app/Controller/SongsController.php(521): CakeResponse->file('/srv/http/soner...', Array)
#1 [internal function]: SongsController->download('18943')
#2 /srv/http/sonerezh/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SongsController), Array)
#3 /srv/http/sonerezh/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /srv/http/sonerezh/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SongsController), Object(CakeRequest))
#5 /srv/http/sonerezh/app/webroot/index.php(107): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

**Comment by ltGuillaume** [comment]
Fix here: https://github.com/Sonerezh/sonerezh/issues/190#issuecomment-225830822
