### ISSUE TITLE
Error: [CakeSessionException] Unable to configure the session, setting session.use_trans_sid failed.

### ISSUE THREAD

**Issue by niklaas** [Sonerezh/sonerezh#171]
Using the master branch, I get the following error

```
Error: [CakeSessionException] Unable to configure the session, setting session.use_trans_sid failed.
Request URL: /install
```

on the following system:

```
FreeBSD box.niklaas.eu 10.2-RELEASE-p14 FreeBSD 10.2-RELEASE-p14 #0: Wed Mar 16 20:46:12 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

with the following nginx settings:

```
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       80;
        listen       [::]:80;
        server_name  sub.domain.tld;
        root   /usr/local/www/sub.domain.tld/sonerezh/app/webroot;
        index index.php;
        location / {
            try_files $uri $uri/ /index.php?$args;
            expires 14d;
            add_header Cache-Control 'public';
        }
        location ~ \.php$ {
            fastcgi_pass   unix:/var/run/php-fpm.sock;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        }
    }
}
```

and this is the full trace:

```
2016-04-01 12:21:05 Notice: Notice (8): Undefined variable: sync_token in [/jail/usr/local/www/sub.domain.tld/sonerezh/app/View/Layouts/default.ctp, line 140]
Trace:
include - APP/View/Layouts/default.ctp, line 140
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
ExceptionRenderer::_outputMessage() - CORE/Cake/Error/ExceptionRenderer.php, line 289
ExceptionRenderer::error500() - CORE/Cake/Error/ExceptionRenderer.php, line 257
ExceptionRenderer::render() - CORE/Cake/Error/ExceptionRenderer.php, line 187
ErrorHandler::handleException() - CORE/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??
```

```
2016-04-01 12:21:05 Warning: Warning (2): register_shutdown_function(): Invalid shutdown callback 'session_write_close' passed in [/jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Model/Datasource/CakeSession.php, line 154]
Trace:
register_shutdown_function - [internal], line ??
CakeSession::init() - CORE/Cake/Model/Datasource/CakeSession.php, line 154
CakeSession::_cookieName() - CORE/Cake/Model/Datasource/CakeSession.php, line 549
CakeSession::_hasSession() - CORE/Cake/Model/Datasource/CakeSession.php, line 561
CakeSession::check() - CORE/Cake/Model/Datasource/CakeSession.php, line 231
AuthComponent::user() - CORE/Cake/Controller/Component/AuthComponent.php, line 660
AppController::beforeFilter() - APP/Controller/AppController.php, line 93
InstallersController::beforeFilter() - APP/Controller/InstallersController.php, line 20
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - CORE/Cake/Controller/Controller.php, line 676
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2016-04-01 12:21:05 Error: [CakeSessionException] Unable to configure the session, setting session.use_trans_sid failed.
Request URL: /install
Stack Trace:
#0 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Model/Datasource/CakeSession.php(550): CakeSession::_configureSession()
#1 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Model/Datasource/CakeSession.php(561): CakeSession::_cookieName()
#2 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Model/Datasource/CakeSession.php(231): CakeSession::_hasSession()
#3 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Controller/Component/AuthComponent.php(660): CakeSession::check('Auth.User')
#4 /jail/usr/local/www/sub.domain.tld/sonerezh/app/Controller/AppController.php(93): AuthComponent::user()
#5 /jail/usr/local/www/sub.domain.tld/sonerezh/app/Controller/InstallersController.php(20): AppController->beforeFilter()
#6 [internal function]: InstallersController->beforeFilter(Object(CakeEvent))
#7 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#9 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /jail/usr/local/www/sub.domain.tld/sonerezh/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(InstallersController), Object(CakeRequest))
#11 /jail/usr/local/www/sub.domain.tld/sonerezh/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

No errors in nginx log. The following versions are installed:

```
# pkg info | grep php
php56-5.6.19                   PHP Scripting Language
php56-gd-5.6.19                The gd shared extension for php
php56-mysql-5.6.19             The mysql shared extension for php
php56-pdo-5.6.19               The pdo shared extension for php
php56-pdo_mysql-5.6.19         The pdo_mysql shared extension for php
```

On the web page it says:

```
An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

```

Any ideas what could be the issue here?

**Comment by atomiix** [comment]
Hi !

I think maybe your php configuration disables the *ini_set* function.
Look at your *php.ini* file and check that *ini_set* is not in the *disabled_functions* directive.

**Comment by niklaas** [comment]
atomiix [2016-04-01 05:00 -0700] :

>    I think maybe your php configuration disables the ini_set function.
>    Look at your php.ini file and check that ini_set is not in the
>    disabled_functions directive.

Thanks for your help.

This would be it, wouldn't?

```
; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions =
```

So I guess that's not the case. Or do you think of something else?

**Comment by atomiix** [comment]
OK so, the problem is not here.

Maybe you can check if the function _ini_set_ is still working by creating a simple php file with : 
`<?php`
`echo ini_set('display_errors', 1);`
`?>`

and look if the result is 1 or 0.

**Comment by niklaas** [comment]
atomiix [2016-04-01 05:11 -0700] :

>    Maybe you can check if the function ini_set is still working by
>    creating a simple php file with :
>    <?php
>    echo ini_set('display_errors', 1);
>    ?>

I tried that and got no output. After reading the following [1] on
StackOverflow, It tested whether ini_set() is working by changing
`display_errors` and running `phpino()` afterwards.

> I did some research on this, and it turns out that sometimes ini_set will not
> return FALSE, but an empty string. This is mentioned in the URL pointed out
> by gabriel1836. The best way to check if it works is to first check the
> disable_functions flag in php.ini to see if it is disabled, and then (if it
> is not disabled), change a value with it, and echo phpinfo() immediately
> after. If the value is changed under the local column, then you know ini_set
> works.

ini_set() works, I could change the variable.

    1: http://stackoverflow.com/questions/247152/how-do-i-check-if-ini-set-is-enabled-either-in-the-global-php-ini-or-in-my-php

**Comment by atomiix** [comment]
OK It's strange because as you saw, sometimes ini_set will not return false but an empty string but when it return true, it should print "1". So maybe in your case ini_set is working but not returning true :confounded:. 

So try this : 
`<?php`
`if(ini_set('display_errors', 1) === false) {`
`echo "Doesn't work";`
`}`

This is actually almost the same part of code which is crashing in your case from cakephp.
[Look at this line](https://github.com/Sonerezh/sonerezh/blob/master/lib/Cake/Model/Datasource/CakeSession.php#L515).

That will help us to find if the issue is linked to ini_set or to the session :wink:

**Comment by niklaas** [comment]
Thanks for your help. I got a blank page with your example. To assert that I get some response I tried the following
```
<?php
if(ini_set('display_errors', 1) === false) {
echo "Doesn't work";
} else {                                                                                                        
    echo "Does work";                                                                                           
} 
?>
```
and got

"Does work". So it's not ini_set but the session?

**Comment by niklaas** [comment]
Well, I eventually found what caused the problem. :-) My system was rather bare-bones and, as you saw above, I haven't had a lot of php packages installed. You mentioning »session« pointed me to the right direction: I missed to install php56-session... Simple mistake. I thought the module included in the core php56 package. Thanks a lot again!
