### ISSUE TITLE
The import process failed with invalid metadata

### ISSUE THREAD

**Issue by ArthurHoaro** [Sonerezh/sonerezh#192]
Hi! First install, using PostgreSQL database.

``` sh
$ Console/cake sonerezh import -r /home/subsonic/music

Welcome to CakePHP v2.8.1 Console
---------------------------------------------------------------
App : app
Path: /var/www/html/sonerezh/app/
---------------------------------------------------------------
[INFO] Scan /home/subsonic/music...
[INFO] Found 182742 audio files (0 already in the database). Continue? (yes/no) 
[yes] > 
[Bunch of warnings telling me about empty metadata]

[INFO] Run import: [1%] [                                             ]Error: SQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  syntaxe en entrée invalide pour l'entier : « 2003 03 11 »
LINE 1: ...lash', 'The Essential Clash, Disc 2', 20, '3:51', '2003 03 1...
                                                             ^
#0 /var/www/html/sonerezh/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/sonerezh/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO "pu...', Array)
#2 /var/www/html/sonerezh/lib/Cake/Model/Datasource/DboSource.php(1019): DboSource->execute('INSERT INTO "pu...')
#3 /var/www/html/sonerezh/lib/Cake/Model/Model.php(1933): DboSource->create(Object(Song), Array, Array)
#4 /var/www/html/sonerezh/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/html/sonerezh/app/Console/Command/SonerezhShell.php(128): Model->save(Array)
#6 /var/www/html/sonerezh/lib/Cake/Console/Shell.php(458): SonerezhShell->import()
#7 /var/www/html/sonerezh/lib/Cake/Console/ShellDispatcher.php(212): Shell->runCommand('import', Array)
#8 /var/www/html/sonerezh/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#9 /var/www/html/sonerezh/app/Console/cake.php(36): ShellDispatcher::run(Array)
#10 {main}
```

The import crashed trying to import invalid metadata and insert it in the database ("2003 03 11" isn't a valid integer). However, I'm not going to fix them file by file. 

An additional data verification would be nice. 

EDIT: I also had a symlink loop, I obviously don't have 180k music files.

**Comment by lGuillaume124** [comment]
Hi,
Could you be more precise about the symlink loop please?

**Comment by ArthurHoaro** [comment]
`/home/subsonic/music/music` was pointing to `/home/subsonic/music`
