### ISSUE TITLE
Can't install the 1.1.3: blank page

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#240]
Hi!

I screwed up my upgrade to 1.1.3, so I decided to wipe out everything (the sonerezh folder and the database) and start fresh!

But I got some problems... when I got to the /install URL, I got a blank page. After checking in my Nginx logs, I caught this in access log:

```
xxx.xxx.xxx.xxx - - [18/Dec/2016:13:32:43 -0500] "GET /install HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0"
```

And in the error log:

```
PHP message: PHP Warning:  /var/www/sonerezh/app/tmp/cache/persistent/ is not writable in /var/www/sonerezh/lib/Cake/Cache/Engine/FileEngine.php on line 385
PHP message: PHP Fatal error:  Uncaught exception 'CacheException' with message 'Cache engine "_cake_core_" is not properly configured. Ensure required extensions are installed, and credentials/permissions are correct' in /var/www/sonerezh/lib/Cake/Cache/Cache.php:186
Stack trace:
#0 /var/www/sonerezh/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_')
#1 /var/www/sonerezh/app/Config/core.php(376): Cache::config('_cake_core_', Array)
#2 /var/www/sonerezh/lib/Cake/Core/Configure.php(72): include('/home/sonerezh/...')
#3 /var/www/sonerezh/lib/Cake/bootstrap.php(431): Configure::bootstrap(true)
#4 /var/www/sonerezh/app/webroot/index.php(90): include('/home/sonerezh/...')
#5 {main}
  thrown in /var/www/sonerezh/lib/Cake/Cache/Cache.php on line 186" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxxxxxx.com, request: "GET /install HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxxxxxx.com"
```

So it seems that `/var/www/sonerezh/app/tmp/cache/persistent/` doesn't have the right permissions by default.

**Comment by MightyCreak** [comment]
It's strange though... although I did the `sudo chown -R www-data: sonerezh` like in the documentation and that nginx and php-fpm should be running as www-data, I don't see how I can't have permissions problems..

**Comment by MightyCreak** [comment]
OK nevermind, I restarted all the services (nginx, php5-fpm and mysql) and now it works.
