### ISSUE TITLE
Cannot add a user

### ISSUE THREAD

**Issue by Linuxine** [Sonerezh/sonerezh#246]
Hello,

I have a fresh install of sonerezh 1.1.3, seems nice, I have managed to import and play a few files, but when trying to add a user, the pop up close without errors, but doing nothing. In the error.log in app/tmp/logs, I get this error:

```
2016-12-22 11:06:23 Error: [BadRequestException] The request has been black-holed
Request URL: /music/users/add?url=users%2Fadd
Stack Trace:
#0 /var/www/sonerezh/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(UsersController), 'auth')
#1 [internal function]: SecurityComponent->startup(Object(UsersController))
#2 /var/www/sonerezh/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#3 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#4 /var/www/sonerezh/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#5 /var/www/sonerezh/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/sonerezh/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/sonerezh/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/sonerezh/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

I guess there maybe something misconfigured, but I am sorry, I did not managed to find any information on the net ? 
Thanks for the help !

**Comment by MightyCreak** [comment]
It might be linked to #245 who also has a black-holed error, but in a different context.

How did you have this neat callstack? so that @andynosaur could try to try to get it as well and see if the callstack is the same.

Thanks!

**Comment by Linuxine** [comment]
Hi, 

Actually I didn't do anything more than said I the first comment, installed Sonerezh (dezipping in /var/www, apache rights, go to the install url, fill the field about the database) and tried to create a user in the interface via the "new user" button...

**Comment by lGuillaume124** [comment]
Hi,
The URL where the form is posted shouldn't look like this. It should be something like ```/music/user/add?ajax=true```.

**Comment by Linuxine** [comment]
So you mean this could be a configuration issue ?

**Comment by atomiix** [comment]
Did you try to clear your cache/cookie and try again ?

**Comment by Amgine0** [comment]
Note: I have configured $smtp but NOT $default because my server's IP is part of an ISP block which is blacklisted by most mail servers. 

2017-02-01 21:51:29 Error: [ConfigureException] Unknown email configuration "default".
Request URL: /users/add
Stack Trace:
#0 /raid/www/sonerezh/lib/Cake/Network/Email/CakeEmail.php(1148): CakeEmail->_applyConfig('default')
#1 /raid/www/sonerezh/lib/Cake/Network/Email/CakeEmail.php(362): CakeEmail->config('default')
#2 /raid/www/sonerezh/app/Lib/Event/UsersEventListener.php(22): CakeEmail->__construct('default')
#3 /raid/www/sonerezh/lib/Cake/Event/CakeEventManager.php(243): UsersEventListener->sendUserCreationEmail(Object(CakeEvent))
#4 /raid/www/sonerezh/app/Model/User.php(123): CakeEventManager->dispatch(Object(CakeEvent))
#5 /raid/www/sonerezh/lib/Cake/Event/CakeEventManager.php(241): User->afterSave(true, Array)
#6 /raid/www/sonerezh/lib/Cake/Model/Model.php(1961): CakeEventManager->dispatch(Object(CakeEvent))
#7 /raid/www/sonerezh/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#8 /raid/www/sonerezh/app/Controller/UsersController.php(51): Model->save(Array)
#9 [internal function]: UsersController->add()
#10 /raid/www/sonerezh/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#11 /raid/www/sonerezh/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /raid/www/sonerezh/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#13 /raid/www/sonerezh/app/webroot/index.php(107): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}

**Comment by Amgine0** [comment]
Renaming to $default resolved the above.

**Comment by Ma5onic** [comment]
^
What exactly did you rename? i am getting similar logs when trying to add a new user
