### ISSUE TITLE
Failed to import track

### ISSUE THREAD

**Issue by PixiBixi** [Sonerezh/sonerezh#267]
Hi, 

I try to import lots of files with the console, but i've got this error :

`[INFO] Run importError: [] operator not supported for strings
#0 /var/www/music/app/Vendor/Getid3/module.audio.mp3.php(1075): getid3_mp3->decodeMPEGaudioHeader(206, Array, false)
#1 /var/www/music/app/Vendor/Getid3/module.audio.mp3.php(960): getid3_mp3->RecursiveFrameScanning(206, 623, false)
#2 /var/www/music/app/Vendor/Getid3/module.audio.mp3.php(1417): getid3_mp3->decodeMPEGaudioHeader(206, Array, true)
#3 /var/www/music/app/Vendor/Getid3/module.audio.mp3.php(34): getid3_mp3->getOnlyMPEGaudioInfo(206)
#4 /var/www/music/app/Vendor/Getid3/getid3.php(428): getid3_mp3->Analyze()
#5 /var/www/music/app/Lib/SongManager/SongManager.php(16): getID3->analyze('/home/barracuda...')
#6 /var/www/music/app/Console/Command/SonerezhShell.php(117): SongManager->parseMetadata()
#7 /var/www/music/lib/Cake/Console/Shell.php(458): SonerezhShell->import()
#8 /var/www/music/lib/Cake/Console/ShellDispatcher.php(212): Shell->runCommand('import', Array)
#9 /var/www/music/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 /var/www/music/app/Console/cake.php(36): ShellDispatcher::run(Array)
#11 {main}
`
If someone have an idea?

**Comment by Azphreal** [comment]
I think it means exactly what it says. Some of your audio files have `[]` in them. I'm getting the same error and checked my music collection, and I have about twenty files with square brackets in them. I tried importing directories that didn't have those files, and it worked fine.

**Comment by PixiBixi** [comment]
O'right, thanks :)

**Comment by xpac27** [comment]
I'm getting the exact same error on multiple files but those files don't seem to have any [ or ] in any of their tags.

@Azphreal Is that what you meant?
@PixiBixi Did you manage to fix your issue?

**Comment by xpac27** [comment]
According to [this issue](https://github.com/JamesHeinrich/getID3/issues/97) updating getID3 to v1.9.14 did fix the issue.

**Comment by xpac27** [comment]
Shouldn't this be closed and an _"Update getID3 lib"_ task bed added to the 1.1.4 Milestone? 😃

**Comment by gbip** [comment]
I still have the same problem with version 1.2 ... @xpac27 what is the fix ?

**Comment by gbip** [comment]
Ok so I figured out the fix by myself, youd need to replace the files in `app/Vendor/Getid3` by the latest one from the [original repo](https://github.com/JamesHeinrich/getID3).
