### ISSUE TITLE
PDOException - settings page inaccessible

### ISSUE THREAD

**Issue by pacija** [Sonerezh/sonerezh#303]
Hi,

I have a bunch of problems with collection maintenance, but this one actually writes something into log file so I guess it shouldn't be hard for devs to troubleshoot:

```
2017-05-15 15:51:22 Error: [PDOException] SQLSTATE[HY000]: General error: 126 Incorrect key file for table '/tmp/#sql40cb_5daf_2.MYI'; try to repair it
Request URL: /settings
Stack Trace:
#0 /usr/local/www/sonerezh-1.1.3/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /usr/local/www/sonerezh-1.1.3/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT COUNT(*)...', Array)
#2 /usr/local/www/sonerezh-1.1.3/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('SELECT COUNT(*)...', Array, Array)
#3 /usr/local/www/sonerezh-1.1.3/lib/Cake/Model/Datasource/DboSource.php(1113): DboSource->fetchAll('SELECT COUNT(*)...', Array)
#4 /usr/local/www/sonerezh-1.1.3/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Song), Array)
#5 /usr/local/www/sonerezh-1.1.3/lib/Cake/Model/Model.php(3003): Model->_readDataSource('count', Array)
#6 /usr/local/www/sonerezh-1.1.3/app/Controller/SettingsController.php(67): Model->find('count', Array)
#7 [internal function]: SettingsController->index()
#8 /usr/local/www/sonerezh-1.1.3/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SettingsController), Array)
#9 /usr/local/www/sonerezh-1.1.3/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /usr/local/www/sonerezh-1.1.3/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SettingsController), Object(CakeRequest))
#11 /usr/local/www/sonerezh-1.1.3/app/webroot/index.php(107): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```
This is on FreeBSD 11.0-RELEASE-p10 amd64, with mysql56-server-5.6.36 and php70-pdo_mysql-7.0.18. Apache/Sonerezh and MySQL are on different servers/jails. I also see the following in mysql error log:

```
2017-05-15 15:51:22 16587 [ERROR] Got an error from unknown thread, /wrkdirs/usr/ports/databases/mysql56-server/work/mysql-5.6.36/storage/myisam/mi_write.c:223
2017-05-15 15:53:39 16587 [ERROR] /usr/local/libexec/mysqld: Incorrect key file for table '/tmp/#sql40cb_5db9_2.MYI'; try to repair it
2017-05-15 15:53:39 16587 [ERROR] /usr/local/libexec/mysqld: Incorrect key file for table '/tmp/#sql40cb_5db9_2.MYI'; try to repair it
2017-05-15 15:53:39 16587 [ERROR] Got an error from unknown thread, /wrkdirs/usr/ports/databases/mysql56-server/work/mysql-5.6.36/storage/myisam/mi_write.c:223
2017-05-15 15:59:58 16587 [ERROR] /usr/local/libexec/mysqld: Incorrect key file for table '/tmp/#sql40cb_5deb_2.MYI'; try to repair it
2017-05-15 15:59:58 16587 [ERROR] /usr/local/libexec/mysqld: Incorrect key file for table '/tmp/#sql40cb_5deb_2.MYI'; try to repair it
2017-05-15 15:59:58 16587 [ERROR] Got an error from unknown thread, /wrkdirs/usr/ports/databases/mysql56-server/work/mysql-5.6.36/storage/myisam/mi_write.c:223
2017-05-15 16:00:06 16587 [ERROR] /usr/local/libexec/mysqld: Incorrect key file for table '/tmp/#sql40cb_5e03_2.MYI'; try to repair it
2017-05-15 16:00:06 16587 [ERROR] /usr/local/libexec/mysqld: Incorrect key file for table '/tmp/#sql40cb_5e03_2.MYI'; try to repair it
2017-05-15 16:00:06 16587 [ERROR] Got an error from unknown thread, /wrkdirs/usr/ports/databases/mysql56-server/work/mysql-5.6.36/storage/myisam/mi_write.c:223
```
This appears to be related to growth of 'songs' table - it works fine up to ~7,167 rows (3.1Mib). As soon as I add new album, and 'songs' table has ~7,194 rows, I get above errors and can't access settings page.

*Update*: I deleted one by one track from 'songs' table, and I got my settings page back when I reduced it to 7171 rows. Adding any track as 7172th row renders settings page inaccessible.

Any help much appreciated.

**Comment by pacija** [comment]
I've spin up another jail with mysql57-server-5.7.18, and I don't get above error. I guess the problem is not related to sonerezh itself, but to [bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219238) in FreeBSD's databases/mysql56-server port.

I'm closing the issue.
