### ISSUE TITLE
SQLite unable to import songs via command line, missing table main.songs

### ISSUE THREAD

**Issue by hwrng** [Sonerezh/sonerezh#326]
Version 1.1.3
```
xxx@xxx:/www/xxx.xxx/sonerezh/app# Console/cake sonerezh import -r /mnt/audio

Welcome to CakePHP v2.8.1 Console
---------------------------------------------------------------
App : app
Path: /www/xxx.xxx/sonerezh/app/
---------------------------------------------------------------
[INFO] Scan /mnt/audio...
Error: SQLSTATE[HY000]: General error: 1 no such table: main.songs
#0 /www/xxx.xxx/sonerezh/lib/Cake/Model/Datasource/DboSource.php(459): PDO->prepare('SELECT "Song"."...', Array)
#1 /www/xxx.xxx/sonerezh/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT "Song"."...', Array)
#2 /www/xxx.xxx/sonerezh/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('SELECT "Song"."...', Array, Array)
#3 /www/xxx.xxx/sonerezh/lib/Cake/Model/Datasource/DboSource.php(1113): DboSource->fetchAll('SELECT "Song"."...', Array)
#4 /www/xxx.xxx/sonerezh/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Song), Array)
#5 /www/xxx.xxx/sonerezh/lib/Cake/Model/Model.php(3003): Model->_readDataSource('list', Array)
#6 /www/xxx.xxx/sonerezh/app/Console/Command/SonerezhShell.php(62): Model->find('list', Array)
#7 /www/xxx.xxx/sonerezh/lib/Cake/Console/Shell.php(458): SonerezhShell->import()
#8 /www/xxx.xxx/sonerezh/lib/Cake/Console/ShellDispatcher.php(212): Shell->runCommand('import', Array)
#9 /www/xxx.xxx/sonerezh/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 /www/xxx.xxx/sonerezh/app/Console/cake.php(36): ShellDispatcher::run(Array)
#11 {main}
```

**Comment by stognola** [comment]
same here today, i'm using sqlite
