### ISSUE TITLE
Cli Import Fails : undefined function "pcntl_signal()"

### ISSUE THREAD

**Issue by gbip** [Sonerezh/sonerezh#340]
Hi,
I just installed sonerezh on a server running FreeBSD 11.2 with php 7.2 and nginx 11.14.
When importing my song, the web interface hang up at around 20% (I left it running for a pretty long time).
When importing from the CLI, I have the following log :

```
[INFO] Found 1072 audio files (0 already in the database). Continue? (yes/no) 
[yes] > yes
[INFO] Run importError: Call to undefined function pcntl_signal()
#0 /usr/local/www/sonerezh/lib/Cake/Console/Shell.php(458): SonerezhShell->import()
#1 /usr/local/www/sonerezh/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('import', Array)
#2 /usr/local/www/sonerezh/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#3 /usr/local/www/sonerezh/app/Console/cake.php(36): ShellDispatcher::run(Array)
#4 {main}
```

I checked `php.ini` for the value of `disabled_functions` but it is empty. 

Since I couldn't find any help I decided to open this issue.

**Comment by gbip** [comment]
So, the solution is to check the output of `php -me` to see if pcntl is present.
If not, install it via `pkg install pcntl`.
