### ISSUE TITLE
Can't create new user

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#74]
I'm trying to create my 4th Sonerezh user. When I click the `Create` button, the user list refreshes, but no user is added. My `error.log`:

```
2015-03-23 12:40:31 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Setting.enable_mail_notification' in 'field list'
Request URL: /music/users/add?ajax=true
Stack Trace:
#0 /var/www/music/lib/Cake/Model/Datasource/DboSource.php(460): PDOStatement->execute(Array)
#1 /var/www/music/lib/Cake/Model/Datasource/DboSource.php(426): DboSource->_execute('SELECT `Setting...', Array)
#2 /var/www/music/lib/Cake/Model/Datasource/DboSource.php(668): DboSource->execute('SELECT `Setting...', Array, Array)
#3 /var/www/music/lib/Cake/Model/Datasource/DboSource.php(1106): DboSource->fetchAll('SELECT `Setting...', false)
#4 /var/www/music/lib/Cake/Model/Model.php(3022): DboSource->read(Object(Setting), Array)
#5 /var/www/music/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#6 /var/www/music/app/Lib/Event/UsersEventListener.php(17): Model->find('first', Array)
#7 [internal function]: UsersEventListener->sendUserCreationEmail(Object(CakeEvent))
#8 /var/www/music/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#9 /var/www/music/app/Model/User.php(117): CakeEventManager->dispatch(Object(CakeEvent))
#10 [internal function]: User->afterSave(true, Array)
#11 /var/www/music/lib/Cake/Event/CakeEventManager.php(241): call_user_func_array(Array, Array)
#12 /var/www/music/lib/Cake/Model/Model.php(1957): CakeEventManager->dispatch(Object(CakeEvent))
#13 /var/www/music/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#14 /var/www/music/app/Controller/UsersController.php(50): Model->save(Array)
#15 [internal function]: UsersController->add()
#16 /var/www/music/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#17 /var/www/music/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#18 /var/www/music/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#19 /var/www/music/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
```

Using the latest commit cdad8ab40bfc82fd0a6dae5dbc1325a426515c81

What should I do?

**Comment by FoxiesCuties** [comment]
Hello,

Try this request 
```
ALTER TABLE `settings` ADD `enable_mail_notification` TINYINT(1) NOT NULL DEFAULT '0' ;
```

**Comment by lGuillaume124** [comment]
Yes, that's right, you are using the development branch, which is not a good idea ^^

You can also use the CakePHP console to update your table:

```
sudo -u www-data app/Console/cake schema update sonerezh
```

**Comment by nodiscc** [comment]
@lGuillaume124 I'm using the `1.0.0-beta` branch for testing purposes. `sudo -u www-data app/Console/cake schema update sonerezh` did the trick. You may want to make sonerezh update the database schema automatically when the DB is updated by clicking the button. Thanks for your help!
